# docker-compose.prod.yml
services:
  next-app:
    container_name: next-app
    build:
      context: ./bkfire
      dockerfile: Dockerfile
      args:
        BASE_URL: https://YOUR_DOMAIN_OR_IP
    env_file:
      - ./bkfire/.env.production
    ports:
      - "3000:3000"

  nginx:
    image: nginx:alpine
    container_name: nginx-prod
    depends_on:
      - next-app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"