# docker-compose.dev.yml
version: "3.9"

services:
  next-app:
    container_name: next-app
    build:
      context: ./bkfire
      dockerfile: Dockerfile.dev
    env_file:
      - ./bkfire/.env.development
      - ./bkfire/.env.local
    volumes:
      - ./bkfire:/app
    ports:
      - "3000:3000"

  nginx:
    image: nginx:alpine
    container_name: nginx-dev
    depends_on:
      - next-app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"